# Project information
site_name: PsBurn
site_url: https://360modder.github.io/psburn/
site_author: 360modder
site_description: psburn is cross platform tool to compile dynamic powershell scripts into platform specific executables by encapsulating it inside a python or c# program.

# Repository
repo_url: https://github.com/360modder/psburn
repo_name: 360modder/psburn
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 360modder

# Configuration
theme:
  name: material
  favicon: images/favicon.png
  
  features:
    - navigation.tabs
    - navigation.instant

  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/360modder

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installations: gettingstarted/installations.md
    - Workflow: gettingstarted/workflow.md
    - Compiling Powershell Scripts: gettingstarted/compilingpsscripts.md
    - Argparse Integration: gettingstarted/argparseintegration.md
  - Usage:
    - Creating Self Contained Executable: usage/creatingselfcontainedexecutable.md
    - Embedding Resources:
      - usage/embeddingresources/embeddingresources.md
      - Invoke Sub Scripts: usage/embeddingresources/invokesubscripts.md
    - No Extract: usage/noextract.md
  - Documentation:
    - Python:
      - Cross: documentation/python/cross.md
      - CBuild: documentation/python/cbuild.md
    - C#:
      - Create: documentation/csharp/create.md
      - Build: documentation/csharp/build.md
    - Argparse: documentation/argparse.md
    - Runtime: documentation/runtime.md
